import sys
text = open('pccontrol/jsruntime/TLinkautoJSLegacyTaskAdapter.mm').read()

replacements = {
    "TASK_SCREEN_SIZE": "TASK_SCREEN_SIZE", # Already standard TASK_SCREEN_SIZE ??? Wait let's check what it should be.
    "TASK_APP_OPEN": "TASK_PROCESS_BRING_FOREGROUND",
    "TASK_APP_LIST": "TASK_LIST_BUNDLES",
    "TASK_APP_OPEN_URL": "TASK_OPEN_URL",
    "TASK_CONNECTIVITY_WIFI": "TASK_WIFI",
    "TASK_CONNECTIVITY_BLUETOOTH": "TASK_BLUETOOTH",
    "TASK_CONNECTIVITY_SET_WIFI": "TASK_WIFI",
    "TASK_CONNECTIVITY_SET_BLUETOOTH": "TASK_BLUETOOTH",
    "TASK_SCREEN_MATCH_COLOR": "TASK_COLOR_SEARCHER",
    "TASK_SCREEN_MATCH_IS_COLORS": "TASK_COLOR_SEARCHER", # Will verify mapping
    "TASK_SCREEN_MATCH_MULTI_COLOR": "TASK_COLOR_SEARCHER",
    "TASK_SCREEN_CAPTURE": "TASK_SCREENSHOT",
    "TASK_SCREEN_CAPTURE_TO": "TASK_SCREENSHOT", # Wait
    "TASK_SCREEN_CAPTURE_REGION": "TASK_SCREENSHOT",
    "TASK_SCREEN_CAPTURE_SAVE_TO_ALBUM": "TASK_SCREENSHOT",
    "TASK_SCREEN_CAPTURE_CLEAR_ALBUM": "TASK_SCREENSHOT",
    "TASK_NATIVE_HARDWARE_KEY": "TASK_HARDWARE_KEY",
    "TASK_NATIVE_HARDWARE_KEY_PRESS": "TASK_HARDWARE_KEY",
    "TASK_NATIVE_KEEP_AWAKE": "TASK_KEEP_AWAKE",
}
