import re

text = open("pccontrol/jsruntime/TLinkautoJSLegacyTaskAdapter.mm").read()

mappings = {
    "TASK_SCREEN_SIZE": "TASK_SCREENSHOT", # it usually is handled internally or using a different task ID, wait.
    "TASK_APP_OPEN": "TASK_PROCESS_BRING_FOREGROUND",
    "TASK_APP_LIST": "TASK_LIST_BUNDLES",
    "TASK_APP_OPEN_URL": "TASK_OPEN_URL",
    "TASK_CONNECTIVITY_WIFI": "TASK_WIFI",
    "TASK_CONNECTIVITY_BLUETOOTH": "TASK_BLUETOOTH",
    "TASK_CONNECTIVITY_SET_WIFI": "TASK_WIFI",
    "TASK_CONNECTIVITY_SET_BLUETOOTH": "TASK_BLUETOOTH",
    "TASK_SCREEN_MATCH_COLOR": "TASK_COLOR_SEARCHER",
    "TASK_SCREEN_MATCH_IS_COLORS": "TASK_COLOR_SEARCHER",
    "TASK_SCREEN_MATCH_MULTI_COLOR": "TASK_COLOR_SEARCHER",
    "TASK_SCREEN_CAPTURE": "TASK_SCREENSHOT",
    "TASK_SCREEN_CAPTURE_TO": "TASK_SCREENSHOT",
    "TASK_SCREEN_CAPTURE_REGION": "TASK_SCREENSHOT",
    "TASK_SCREEN_CAPTURE_SAVE_TO_ALBUM": "TASK_SCREENSHOT",
    "TASK_SCREEN_CAPTURE_CLEAR_ALBUM": "TASK_SCREENSHOT",
    "TASK_NATIVE_HARDWARE_KEY": "TASK_HARDWARE_KEY",
    "TASK_NATIVE_HARDWARE_KEY_PRESS": "TASK_HARDWARE_KEY",
    "TASK_NATIVE_KEEP_AWAKE": "TASK_KEEP_AWAKE",
    "TASK_NATIVE_TOUCH_INDICATOR": "TASK_TOUCH_INDICATOR",
    "TASK_NATIVE_KEYBOARD_INSERT": "TASK_TEXT_INPUT",
    "TASK_NATIVE_KEYBOARD_DELETE": "TASK_TEXT_INPUT",
    "TASK_NATIVE_KEYBOARD_CURSOR": "TASK_TEXT_INPUT",
    "TASK_NATIVE_SET_CLIPBOARD": "TASK_TEXT_INPUT", # Wait, I need to check how it actually translates.
    "TASK_NATIVE_GET_CLIPBOARD": "TASK_TEXT_INPUT",
    "TASK_SHOW_ALERT": "TASK_SHOW_ALERT_BOX",
    "TASK_SHOW_DIALOG": "TASK_DIALOG",
    "TASK_CLEAR_DIALOG_VALUES": "TASK_CLEAR_DIALOG",
    "TASK_DEVICE_INFO": "TASK_GET_DEVICE_INFO",
    "TASK_DEVICE_BATTERY": "TASK_GET_DEVICE_INFO",
}

for k, v in mappings.items():
    text = text.replace(k, v)

with open("pccontrol/jsruntime/TLinkautoJSLegacyTaskAdapter.mm", "w") as f:
    f.write(text)
