#!/bin/sh
su mobile -c uicache
echo "mobile ALL=(root) NOPASSWD:/usr/bin/tlinkautob" >> /etc/sudoers
chown -R mobile:mobile /var/mobile/Library/TLinkauto
chmod +x /var/mobile/Library/TLinkauto/coreutils/ScriptRuntime/add_datetime.sh
chown root:wheel /Library/LaunchDaemons/com.tlinkauto.tlinkautod.plist
chmod 644 /Library/LaunchDaemons/com.tlinkauto.tlinkautod.plist
launchctl unload /Library/LaunchDaemons/com.tlinkauto.tlinkautod.plist 2>/dev/null
launchctl load -w /Library/LaunchDaemons/com.tlinkauto.tlinkautod.plist
